# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: m1_perception/model_serving/semantic_embedding_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<m1_perception/model_serving/semantic_embedding_service.proto\"Q\n\x08\x42\x36\x34Image\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x14\n\x0cnum_channels\x18\x04 \x01(\x05\x32t\n\x11SemanticEmbedding\x12,\n\x12GetSpeedEstimation\x12\t.B64Image\x1a\t.B64Image\"\x00\x12\x31\n\x17GetSemanticSegmentation\x12\t.B64Image\x1a\t.B64Image\"\x00\x62\x06proto3')



_B64IMAGE = DESCRIPTOR.message_types_by_name['B64Image']
B64Image = _reflection.GeneratedProtocolMessageType('B64Image', (_message.Message,), {
  'DESCRIPTOR' : _B64IMAGE,
  '__module__' : 'm1_perception.model_serving.semantic_embedding_service_pb2'
  # @@protoc_insertion_point(class_scope:B64Image)
  })
_sym_db.RegisterMessage(B64Image)

_SEMANTICEMBEDDING = DESCRIPTOR.services_by_name['SemanticEmbedding']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B64IMAGE._serialized_start=64
  _B64IMAGE._serialized_end=145
  _SEMANTICEMBEDDING._serialized_start=147
  _SEMANTICEMBEDDING._serialized_end=263
# @@protoc_insertion_point(module_scope)
